---
title: "Rick and Morty's IMDB Scoring"
author: "Mauro"
date: "2022-09-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Best Rick And Morty Season

```{r season, echo=FALSE, message=FALSE, warning=FALSE}
df <- rio::import('rick_morty_imdb.xlsx')

library(dplyr)
library(stringr) 

df <- df %>%
    mutate(across('name', str_replace, "\"", "")) %>%
    mutate(across('name', str_replace, '"', "")) %>% 
    filter(season != 6)

df %>%
    group_by(season) %>%
    summarise_at(vars(rating), list(rating = mean)) %>% 
    arrange(desc(rating))
```

Using the mean IMDB score of every episode we conclude that best season is 3 and the lowest ranked season is the fifth.

# Top 10 episodes

```{r episodes, echo = FALSE}
df %>% slice_max(rating, n = 10) %>% select(name, season, rating)
```

# Worst 10 episodes

```{r episodes_l, echo = FALSE}
df %>% slice_min(rating, n = 10) %>% select(name, season, rating)
```


## Rick and Morty IMDB episode scoring over time

```{r graph, echo=FALSE, message=FALSE, warning=FALSE}
df$date <- as.Date(df$air_date, format="%B %d, %Y")

library(plotly)

fig <- plot_ly(df, x = ~date, y = ~rating, type = 'scatter', mode = 'lines', text = ~name)

fig
```

